// <auto-generated />
namespace Movie_Rental___Backend.DbMovieRental.MovieRentalMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModifyRelationshipTablesVideoGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyRelationshipTablesVideoGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201831524_ModifyRelationshipTablesVideoGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
